config/routes.rb
Rails.application.routes.draw do
  root 'cleaner#new'
  
  post 'cleaner/create'

  get 'cleaner/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cleaner_controller.rb
class CleanerController < ApplicationController
  def new
  end 


  def create 
  
      @script = params[:cleaner][:script]
      @splitted = @script.split("\n")
      count = 0
      tc = ""
      @loops = Hash.new

      @splitted.each{
          |element|
          
          if count % 4 == 1 
          
              tc = "00."+element[3..4].to_s+"."+element[6..7].to_s
 
          
          elsif count % 4 == 2 
           
              eng_dialog = element 
              current = @loops[tc].to_s
              @loops[tc] = current +" "+ eng_dialog
              
          end 
      
          count+= 1 
      
      }

      @loops.each{

          |t, d|
      
      
          puts t + d
        
      
      }
      



  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cleaner_helper.rb
module CleanerHelper
end

app/views/cleaner/create.html.erb
<div class="header">
    <%= image_tag("LDS_Logo.svg") %>
</div>

<div class="container">
<h1>NOTHING GOLD CAN STAY FORMAT</h1>
    <button class="clipboard-btn button" data-clipboard-action="copy" data-clipboard-target="#script">
        Copy!
    </button>
    <table id="script">
        <tr>
            <th>TC</th>
            <th>Personaje</th>
            <th>English</th>
            <th>Diálogo<th>
        </tr>
        
        <% @loops.each do |tc, value|%>
        
            <tr>
                <td class="timecode_text"> <%= tc %>  </td>
                <td></td>
                <td class="english_text"> <%= value %> </td>
                <td></td>
            </tr>

        <% end %>

    </table>

</div>

app/views/cleaner/new.html.erb
<div class="header">
    <%= image_tag("LDS_Logo.svg") %>
</div>


<div class="container-script">

    <h1>NOTHING GOLD CAN STAY FORMAT</h1>
    
    <%= form_for(:cleaner, url: cleaner_create_path) do |f| %>
        
        <%= f.label :script, "Paste format:" %>
        
        <%= f.text_area :script, class: "text-area" %>  
       
        <%= f.submit "SUBMIT", class: "button"%>
         <%= submit_tag("CLEAR", { :name => 'reset', :id => 'reset_button', :type => "reset" }) %>
    <% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Script App | LEXI D&S</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Lato&display=swap' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>